import { Body,Controller,Delete,Get,Param,Post,Put,Query } from '@nestjs/common';
import { CoreService } from './core.service.js';
@Controller()
export class CoreController{
constructor(private readonly s:CoreService){}
@Post('reviews') cr(@Body()b:any){return this.s.createReview(b)} @Get('reviews') rs(@Query('status')q?:string){return this.s.reviews(q)} @Get('reviews/:id') r(@Param('id')i:string){return this.s.review(i)} @Put('reviews/:id') ur(@Param('id')i:string,@Body()b:any){return this.s.updateReview(i,b)} @Delete('reviews/:id') dr(@Param('id')i:string){return this.s.deleteReview(i)}
@Post('review-reminders') cm(@Body()b:any){return this.s.createReminder(b)} @Get('review-reminders') cms(){return this.s.reminders()} @Get('review-reminders/:id') cmi(@Param('id')i:string){return this.s.reminder(i)} @Put('review-reminders/:id') umi(@Param('id')i:string,@Body()b:any){return this.s.updateReminder(i,b)} @Delete('review-reminders/:id') dmi(@Param('id')i:string){return this.s.deleteReminder(i)}
@Post('favourites') af(@Body()b:any){return this.s.addFavourite(b)} @Get('favourites/:customerId') fs(@Param('customerId')i:string){return this.s.favourites(i)} @Delete('favourites/:customerId/:menuItemId') df(@Param('customerId')c:string,@Param('menuItemId')m:string){return this.s.deleteFavourite(c,m)}
@Post('notifications') cn(@Body()b:any){return this.s.createNotification(b)} @Get('notifications') ns(@Query('status')q?:string){return this.s.notifications(q)} @Get('notifications/:id') n(@Param('id')i:string){return this.s.notification(i)} @Put('notifications/:id') un(@Param('id')i:string,@Body()b:any){return this.s.updateNotification(i,b)} @Delete('notifications/:id') dn(@Param('id')i:string){return this.s.deleteNotification(i)}
@Post('gallery') cg(@Body()b:any){return this.s.createGallery(b)} @Get('gallery') gs(@Query('active')q?:string){return this.s.gallery(q)} @Get('gallery/:id') g(@Param('id')i:string){return this.s.galleryItem(i)} @Put('gallery/:id') ug(@Param('id')i:string,@Body()b:any){return this.s.updateGallery(i,b)} @Delete('gallery/:id') dg(@Param('id')i:string){return this.s.deleteGallery(i)}
@Post('contact-messages') cc(@Body()b:any){return this.s.createContact(b)} @Get('contact-messages') cs(@Query('status')q?:string){return this.s.contacts(q)} @Get('contact-messages/:id') c(@Param('id')i:string){return this.s.contact(i)} @Put('contact-messages/:id') uc(@Param('id')i:string,@Body()b:any){return this.s.updateContact(i,b)} @Delete('contact-messages/:id') dc(@Param('id')i:string){return this.s.deleteContact(i)}
@Post('ai-faqs') cf(@Body()b:any){return this.s.createFaq(b)} @Get('ai-faqs') fsq(@Query('active')q?:string){return this.s.faqs(q)} @Get('ai-faqs/:id') f(@Param('id')i:string){return this.s.faq(i)} @Put('ai-faqs/:id') uf(@Param('id')i:string,@Body()b:any){return this.s.updateFaq(i,b)} @Delete('ai-faqs/:id') dfq(@Param('id')i:string){return this.s.deleteFaq(i)}
@Post('ai-knowledge') ck(@Body()b:any){return this.s.createKnowledge(b)} @Get('ai-knowledge') ks(@Query('approved')q?:string){return this.s.knowledge(q)} @Get('ai-knowledge/:id') k(@Param('id')i:string){return this.s.knowledgeItem(i)} @Put('ai-knowledge/:id') uk(@Param('id')i:string,@Body()b:any){return this.s.updateKnowledge(i,b)} @Delete('ai-knowledge/:id') dk(@Param('id')i:string){return this.s.deleteKnowledge(i)}
@Post('audit-logs') ca(@Body()b:any){return this.s.createAudit(b)} @Get('audit-logs') as(@Query('entity')q?:string){return this.s.audits(q)} @Get('audit-logs/:id') a(@Param('id')i:string){return this.s.audit(i)} @Delete('audit-logs/:id') da(@Param('id')i:string){return this.s.deleteAudit(i)}
}
